name: Release Drafter (Changelog)

on:
  push:
    branches:
      - master
  # Allow to be run manually
  workflow_dispatch:
  # Prepare the new "next release" once a release is created
  release:

# Only allow 1 release-drafter build at a time to avoid creating multiple "next" releases
concurrency: "release-drafter"

jobs:
  update_release_draft:
    uses: jenkinsci/.github/.github/workflows/release-drafter.yml@master
